config/routes.rb
Rails.application.routes.draw do

  resources :transfers

  resources :cuentadantes do
    collection { post :import }
  end

  resources :reintegros

  resources :cuentadantes

  resources :floors do
    resources :areas
  end

  resources :areas do
    resources :elementos
  end

  resources :elementos do
    collection { post :import }
  end

  resources :elementos do
    resources :transfers
  end

  resources :elementos do
    resources :reintegros
  end

  resources :events

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#index', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :cargos

  get 'elementos/elementcuenta', :as => :prueba
  get 'pagina/saim'
  get 'pagina/bloqueo'
  get 'pagina/estadisticas'
  get 'pagina/elementosxcuentadantes'
  get 'pagina/elementosxareas'
  get 'pagina/etraspasos'
  get 'pagina/ereintegros'
  get 'pagina/estreintegr'
  get 'pagina/traceability'
  get 'pagina/index'
  get 'pagina/contactenos'
  resources :tipo_elems

  resources :tipo_docs

  
    get 'allelementos/', to: 'elementos#allelementos', as: 'objetos'

    get 'allcuentadantes/', to: 'cuentadantes#allcuentadantes', as: 'objet'

    get 'allreintegros/', to: 'reintegros#allreintegros', as: 'objetos1'
    
    get 'alltransfers/', to: 'transfers#alltransfers', as: 'objetos2'
  

  root 'pagina#saim'

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
	has_many :users, :dependent => :destroy
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]

  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1
  # PATCH/PUT /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargos_url, notice: 'Cargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cargo_params
      params.require(:cargo).permit(:rol, :descripcion, :privilegioVer, :privilegioEditar, :privilegioEleminar, :privilegioCrear)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_form.html.erb
<%= form_for(@cargo) do |f| %>
  <% if @cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
      <% @cargo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.check_box :rol %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :privilegioVer %><br>
    <%= f.check_box :privilegioVer %>
  </div>
  <div class="field">
    <%= f.label :privilegioEditar %><br>
    <%= f.check_box :privilegioEditar %>
  </div>
  <div class="field">
    <%= f.label :privilegioEleminar %><br>
    <%= f.check_box :privilegioEleminar %>
  </div>
  <div class="field">
    <%= f.label :privilegioCrear %><br>
    <%= f.check_box :privilegioCrear %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing cargo</h1>

<%= render 'form' %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

app/views/cargos/index.html.erb
<% if current_user.email == "Saim@gmail.com" %>
<h1>Listing cargos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Privilegiover</th>
      <th>Privilegioeditar</th>
      <th>Privilegioeleminar</th>
      <th>Privilegiocrear</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.nombre %></td>
        <td><%= cargo.descripcion %></td>
        <td><%= cargo.privilegioVer %></td>
        <td><%= cargo.privilegioEditar %></td>
        <td><%= cargo.privilegioEleminar %></td>
        <td><%= cargo.privilegioCrear %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cargo', new_cargo_path %>
<% else %>
    <div class="panel panel-danger">
        <div class="panel-heading">Acceso Denegado</div>
        <div class="panel-body">
            <p>No Esta Autorizado Para Entrar En Este Sitio</p>
        </div>
      </div>
<% end %>

app/views/cargos/new.html.erb
<h1>New cargo</h1>

<%= render 'form' %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cargo.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @cargo.descripcion %>
</p>

<p>
  <strong>Privilegiover:</strong>
  <%= @cargo.privilegioVer %>
</p>

<p>
  <strong>Privilegioeditar:</strong>
  <%= @cargo.privilegioEditar %>
</p>

<p>
  <strong>Privilegioeleminar:</strong>
  <%= @cargo.privilegioEleminar %>
</p>

<p>
  <strong>Privilegiocrear:</strong>
  <%= @cargo.privilegioCrear %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>