config/routes.rb
Rails.application.routes.draw do

  resources :transfers

  resources :cuentadantes do
    collection { post :import }
  end

  resources :reintegros

  resources :cuentadantes

  resources :floors do
    resources :areas
  end

  resources :areas do
    resources :elementos
  end

  resources :elementos do
    collection { post :import }
  end

  resources :elementos do
    resources :transfers
  end

  resources :elementos do
    resources :reintegros
  end

  resources :events

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#index', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :cargos

  get 'elementos/elementcuenta', :as => :prueba
  get 'pagina/saim'
  get 'pagina/bloqueo'
  get 'pagina/estadisticas'
  get 'pagina/elementosxcuentadantes'
  get 'pagina/elementosxareas'
  get 'pagina/etraspasos'
  get 'pagina/ereintegros'
  get 'pagina/estreintegr'
  get 'pagina/traceability'
  get 'pagina/index'
  get 'pagina/contactenos'
  resources :tipo_elems

  resources :tipo_docs

  
    get 'allelementos/', to: 'elementos#allelementos', as: 'objetos'

    get 'allcuentadantes/', to: 'cuentadantes#allcuentadantes', as: 'objet'

    get 'allreintegros/', to: 'reintegros#allreintegros', as: 'objetos1'
    
    get 'alltransfers/', to: 'transfers#alltransfers', as: 'objetos2'
  

  root 'pagina#saim'

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	has_many :traceabilities
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new

  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    
    render action: :new unless @event.save
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'El evento ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description,:user_id, :start, :end)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event, :html => { :class => 'form-horizontal', remote: true } ) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Titulo %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Descripcion %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <label>Persona A Cargo</label><br>
    <%= f.collection_select :user_id, User.all, :id, :nombre, class: "form-control", prompt: "Seleccione una Persona" %>
  </div>
  <div class="field">
    <%= f.label :Fecha_De_Inicio %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :Fecha_De_Finalizacion %><br>
    <%= f.datetime_select :end %>
  </div>
    <div class="actions">
      <%= f.submit "Guardar", class: "btn btn-success" %>
    </div>
<% end %>

app/views/events/create.js.erb
$.lazybox.close();
location.reload();

app/views/events/edit.html.erb
<div class="contenido ">
	<div class="img1"></div>
	<div class="img2"></div>
		<ul class="nav nav-tabs" style="margin-bottom: 15px;">

		</ul>
	<div id="myTabContent" class="tab-content">
  		<div class="tab-pane fade active in cont1" id="inicio">
			<h1>Editar evento</h1>
			<%= render 'form' %>
			<%= button_to 'Ver', @event, method: "get", class: 'btn btn-info' %>
			<%= button_to 'Atras', events_path, method: "get", class: 'btn btn-primary' %>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<script src='assets/javascripts/es.js'></script>
	<div class="img1"></div>
	<div class="img2"></div>
		<%= button_to 'Nuevo Evento', new_event_path, remote: true, :method => "get", class: "btn btn-info nevento" %>
	<div class="contc">
		<div id='calendar'></div>
			<script>
				$(document).ready(function() {

					var date = new Date();
					var d = date.getDate();
					var m = date.getMonth();
					var y = date.getFullYear();

					$('#calendar').fullCalendar({
						header: {
							left: 'prev,next today',
							center: 'title',
							right: 'month,agendaWeek,agendaDay'
						},
						editable: false,
						lang: 'es',
						eventColor: 'white',
							events: {
								url: '/events',
								type: 'GET',
								error: function() {
									alert('there was an error while fetching events!');
								},
									backgroundColor: 'red',
									textColor: 'black'
								}
							}
						);
					}
				);
			</script>
		</div>
<div id='loading' style='display:none'>loading...</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/new.js.erb
$.lazybox("<%= j(render partial: 'form') %>", { onTop: false });

app/views/events/show.html.erb
<div class="contenido ">
  <div class="img1"></div>
  <div class="img2"></div>
    <ul class="nav nav-tabs" style="margin-bottom: 15px;">

    </ul>
  <div id="myTabContent" class="tab-content">
    <div class="tab-pane fade active in cont1" id="inicio">

      <p id="notice">
        <%= notice %>
      </p>

      <p>
        <strong>Titulo</strong>
        <%= @event.title %>
      </p>

      <p>
        <strong>Descripcion:</strong>
        <%= @event.description %>
      </p>
      <p>
        <strong>Persona A Cargo:</strong>
        <%= @event.user.nombre %>
      </p>
      <p>
        <strong>Empieza en:</strong>
        <%= @event.start %>
      </p>

      <p>
        <strong>Termina en:</strong>
        <%= @event.end %>
      </p>

      <%= button_to 'Editar', edit_event_path(@event), method: "get", class: 'btn btn-warning' %>
      <%= link_to '<i class="btn btn-danger btn-xs">Eliminar</i>'.html_safe, event_path(@event), method: :delete, data: { confirm: 'Estas Segur@?' } %>
      <%= button_to 'Atras', events_path, method: "get", class: 'btn btn-success' %>
    </div>
  </div>
</div>