config/routes.rb
Rails.application.routes.draw do

  resources :transfers

  resources :cuentadantes do
    collection { post :import }
  end

  resources :reintegros

  resources :cuentadantes

  resources :floors do
    resources :areas
  end

  resources :areas do
    resources :elementos
  end

  resources :elementos do
    collection { post :import }
  end

  resources :elementos do
    resources :transfers
  end

  resources :elementos do
    resources :reintegros
  end

  resources :events

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#index', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :cargos

  get 'elementos/elementcuenta', :as => :prueba
  get 'pagina/saim'
  get 'pagina/bloqueo'
  get 'pagina/estadisticas'
  get 'pagina/elementosxcuentadantes'
  get 'pagina/elementosxareas'
  get 'pagina/etraspasos'
  get 'pagina/ereintegros'
  get 'pagina/estreintegr'
  get 'pagina/traceability'
  get 'pagina/index'
  get 'pagina/contactenos'
  resources :tipo_elems

  resources :tipo_docs

  
    get 'allelementos/', to: 'elementos#allelementos', as: 'objetos'

    get 'allcuentadantes/', to: 'cuentadantes#allcuentadantes', as: 'objet'

    get 'allreintegros/', to: 'reintegros#allreintegros', as: 'objetos1'
    
    get 'alltransfers/', to: 'transfers#alltransfers', as: 'objetos2'
  

  root 'pagina#saim'

end

app/models/tipo_elem.rb
class TipoElem < ActiveRecord::Base
	has_many :elementos, :dependent => :destroy
end

app/controllers/tipo_elems_controller.rb
class TipoElemsController < ApplicationController
  before_action :set_tipo_elem, only: [:show, :edit, :update, :destroy]

  # GET /tipo_elems
  # GET /tipo_elems.json
  def index
    @tipo_elems = TipoElem.all
  end

  # GET /tipo_elems/1
  # GET /tipo_elems/1.json
  def show
  end

  # GET /tipo_elems/new
  def new
    @tipo_elem = TipoElem.new
  end

  # GET /tipo_elems/1/edit
  def edit
  end

  # POST /tipo_elems
  # POST /tipo_elems.json
  def create
    @tipo_elem = TipoElem.new(tipo_elem_params)

    respond_to do |format|
      if @tipo_elem.save
        format.html { redirect_to @tipo_elem, notice: 'Tipo elem was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_elem }
      else
        format.html { render :new }
        format.json { render json: @tipo_elem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_elems/1
  # PATCH/PUT /tipo_elems/1.json
  def update
    respond_to do |format|
      if @tipo_elem.update(tipo_elem_params)
        format.html { redirect_to @tipo_elem, notice: 'Tipo elem was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_elem }
      else
        format.html { render :edit }
        format.json { render json: @tipo_elem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_elems/1
  # DELETE /tipo_elems/1.json
  def destroy
    @tipo_elem.destroy
    respond_to do |format|
      format.html { redirect_to tipo_elems_url, notice: 'Tipo elem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_elem
      @tipo_elem = TipoElem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_elem_params
      params.require(:tipo_elem).permit(:nombre, :descripcion)
    end
end

app/helpers/tipo_elems_helper.rb
module TipoElemsHelper
end

app/views/tipo_elems/_form.html.erb
<%= form_for(@tipo_elem) do |f| %>
  <% if @tipo_elem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_elem.errors.count, "error") %> prohibited this tipo_elem from being saved:</h2>

      <ul>
      <% @tipo_elem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :Descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/tipo_elems/edit.html.erb
<h1>Editando Tipo De Elemento</h1>

<%= render 'form' %>

<%= link_to 'Ver', @tipo_elem %> |
<%= link_to 'Atras', tipo_elems_path %>

app/views/tipo_elems/index.html.erb
<% if current_user.email == "Saim@gmail.com" %>
<div class="fondc1">
<h1>Listado De Tipos De Elementos</h1>
<div class="panel-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr class="success">
            <th class="centro">Nombre</th>
            <th class="centro">Descripcion</th>
            <th colspan="3" class="centro">Opciones</th>
          </tr>
        </thead>

        <tbody>
          <% @tipo_elems.each do |tipo_elem| %>
            <tr>
              <td><%= tipo_elem.nombre %></td>
              <td><%= tipo_elem.descripcion %></td>
              <td><%= button_to 'Ver', tipo_elem, method: "get", class: 'btn btn-info' %></td>
              <td><%= button_to 'Editar', edit_tipo_elem_path(tipo_elem), method: "get", class: 'btn btn-warning' %></td>
              <td><%= button_to 'Eliminar', tipo_elem, method: :delete, data: { confirm: 'Are you sure?', method: "get" }, class: 'btn btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>
<br>

<%= button_to 'Nuevo Tipo De Elemento', new_tipo_elem_path, method: "get", class: 'btn btn-primary' %>
</div>
<% else %>
    <div class="panel panel-danger">
        <div class="panel-heading">Acceso Denegado</div>
        <div class="panel-body">
            <p>No Esta Autorizado Para Entrar En Este Sitio</p>
        </div>
      </div>
<% end %>

app/views/tipo_elems/new.html.erb
<h1>Nuevo Tipo De Elemento</h1>

<%= render 'form' %>

<%= link_to 'Atras', tipo_elems_path %>

app/views/tipo_elems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tipo_elem.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @tipo_elem.descripcion %>
</p>

<%= link_to 'Editar', edit_tipo_elem_path(@tipo_elem) %> |
<%= link_to 'Atras', tipo_elems_path %>