config/routes.rb
Rails.application.routes.draw do

  resources :transfers

  resources :cuentadantes do
    collection { post :import }
  end

  resources :reintegros

  resources :cuentadantes

  resources :floors do
    resources :areas
  end

  resources :areas do
    resources :elementos
  end

  resources :elementos do
    collection { post :import }
  end

  resources :elementos do
    resources :transfers
  end

  resources :elementos do
    resources :reintegros
  end

  resources :events

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#index', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  resources :cargos

  get 'elementos/elementcuenta', :as => :prueba
  get 'pagina/saim'
  get 'pagina/bloqueo'
  get 'pagina/estadisticas'
  get 'pagina/elementosxcuentadantes'
  get 'pagina/elementosxareas'
  get 'pagina/etraspasos'
  get 'pagina/ereintegros'
  get 'pagina/estreintegr'
  get 'pagina/traceability'
  get 'pagina/index'
  get 'pagina/contactenos'
  resources :tipo_elems

  resources :tipo_docs

  
    get 'allelementos/', to: 'elementos#allelementos', as: 'objetos'

    get 'allcuentadantes/', to: 'cuentadantes#allcuentadantes', as: 'objet'

    get 'allreintegros/', to: 'reintegros#allreintegros', as: 'objetos1'
    
    get 'alltransfers/', to: 'transfers#alltransfers', as: 'objetos2'
  

  root 'pagina#saim'

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :elemento
  belongs_to :cuentadante
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy, :index, :new, :create], except: [:alltransfers]

  # GET /transfers
  # GET /transfers.json
  def index
    @transfers = @elemento.transfers.all
    @areas = Area.all
    @elemento.area_id
  end

  # GET /transfers/1
  # GET /transfers/1.json
  def show
  end

  # GET /transfers/new
  def new
    @transfer = Transfer.new
    @transfer.elemento_id = @elemento.id
  end

  # GET /transfers/1/edit
  def edit
  end

  # POST /transfers
  # POST /transfers.json
  def create
    @transfer = Transfer.new(transfer_params)
    @transfer.elemento_id = @elemento.id
    @transfer.cuentaorigen = @elemento.cuentadante.nombre
    @elemento.cuentadante_id = @transfer.cuentadante_id
    @elemento.save
    respond_to do |format|
      if @transfer.save
        format.html { redirect_to elemento_transfers_path(@elemento), notice: 'Transfer was successfully created.' }
        format.json { render :show, status: :created, location: @transfer }
      else
        format.html { render :new }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfers/1
  # PATCH/PUT /transfers/1.json
  def update
    @transfer = Transfer.find(params[:id])
    @transfer.update_attributes(transfer_params)
    @elemento.cuentadante_id = @transfer.cuentadante_id
    @elemento.save
    respond_to do |format|
      if @transfer.update(transfer_params)
        format.html { redirect_to elemento_transfers_path(@elemento), notice: 'Transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @transfer }
      else
        format.html { render :edit }
        format.json { render json: @transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfers/1
  # DELETE /transfers/1.json
  def destroy
    @transfer.destroy
    respond_to do |format|
      format.html { redirect_to elemento_transfers_url(@elemento), notice: 'Transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def alltransfers
    @transfers = Transfer.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @elemento = Elemento.find(params[:elemento_id])
      @transfer = Transfer.find(params[:id]) if params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transfer_params
      params.require(:transfer).permit(:elemento_id, :cuentadante_id, :fechaTraspaso, :cuentaorigen)
    end
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/transfers/_form.html.erb
<%= form_for [@elemento,@transfer] do |f| %>
  <% if @transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</h2>

      <ul>
      <% @transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel-body">
    <div class="row">
      <div class="col-md-6">
        <div class="col-md-4 col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">
            <% if @transfer.cuentadante_id == nil %>
              <h3 class="centro">Campos Para Registrar Un Traspaso</h3>
            <% else %>
               <h3 class="centro">Campos Para Editar Un Traspaso</h3>
            <% end %>
            </div>
            <div class="panel-body">
              <form role="form">
                <div class="formcentro">
                  <div class="field">
                    <%= f.hidden_field :elemento_id %>
                  </div>
                  <div class="field">
                    <%= f.label :Nombre_Elemento %><br>
                    <%= @elemento.nombre %>
                  </div>
                  <div class="field">
                    <%= f.label :Cuentadante_Origen %><br>
                    <%= @elemento.cuentadante.nombre %>
                  </div>
                  <div class="field">
                    <label>Cuentadante Destino</label><br>
                    <%= f.collection_select :cuentadante_id, Cuentadante.all, :id, :nombre, class: "form-control tams", prompt: "Seleccione Cuentadante Destino" %>
                  </div>
                  <div class="field">
                    <%= f.label :Fecha_Traspaso %><br>
                    <%= f.datetime_select :fechaTraspaso %>
                  </div>
                </div>
                <% if @transfer.cuentadante_id == nil %>
                  <div class="actions mo0g">
                    <%= f.submit "Guardar", class: "btn btn-success" %>
                  </div>
                <% else %>
                  <div class="actions mo0g">
                    <%= f.submit "Actualizar", class: "btn btn-warning" %>
                  </div>              
                <% end %>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/transfers/alltransfers.html.erb
<div class="fondc2" >
<h1>Listado De Traspasos</h1>

<div class="panel-body contabla">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th class="centro">Nombre Elemento</th>
          <th class="centro">Cuentadante Origen</th>
          <th class="centro">Cuentadante Destino</th>
          <th class="centro">Fecha De Traspaso</th>
          <th class="centro">Opciones</th>
        </tr>
      </thead>

      <tbody>
        <% @transfers.each do |transfer| %>
          <tr>
            <td><%= transfer.elemento.nombre %></td>
            <td><%= transfer.cuentaorigen %></td>
            <td><%= transfer.cuentadante.nombre %></td>
            <td><%= transfer.fechaTraspaso %></td>
            <td>
              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><%= image_tag("opcion.png", height: '10', width: '18', class: 'img1')%>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <a href="#">
                      <%= button_to 'Ver', elemento_transfer_path(transfer.elemento,transfer), method: "get", class: 'btn btn-info bottam'%>
                    </a>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/transfers/edit.html.erb
<h1 class="centro">Editar Traspaso</h1>

<%= render 'form' %>
<div class="contdiv">
	<div class="mo0a1">
	<%= button_to 'Ver', elemento_transfer_path(@elemento,@transfer), method: "get", class: 'btn btn-info' %>
	</div>
	<div class="mo0a2">
	<%= button_to 'Back', elemento_transfers_path, method: "get", class: 'btn btn-primary' %>
	</div>
</div>

app/views/transfers/index.html.erb
<div class="fondc2" >
<h1>Listado De Traspasos</h1>

<div class="panel-body contabla">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th class="centro">Nombre Elemento</th>
          <th class="centro">Cuentadante Origen</th>
          <th class="centro">Cuentadante Destino</th>
          <th class="centro">Fecha De Traspaso</th>
          <th class="centro">Opciones</th>
        </tr>
      </thead>

      <tbody>
        <% @transfers.each do |transfer| %>
          <tr>
            <td><%= transfer.elemento.nombre %></td>
            <td><%= transfer.cuentaorigen %></td>
            <td><%= transfer.cuentadante.nombre %></td>
            <td><%= transfer.fechaTraspaso %></td>
            <td>
              <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><%= image_tag("opcion.png", height: '10', width: '18', class: 'img1')%>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <a href="#">
                      <%= button_to 'Ver', elemento_transfer_path(@elemento,transfer), method: "get", class: 'btn btn-info bottam'%>
                    </a>
                  </li>
                  <%#<% if can? :update, transfer %>
                  <%#<li class="divider"></li>
                  <li>
                    <a href="#">
                      <%= button_to 'Editar', edit_elemento_transfer_path(@elemento,transfer), method: "get", class: 'btn btn-warning bottam2' %>
                  <%#  </a>
                  </li>
                  <% end %>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= button_to 'Nuevo Traspaso', new_elemento_transfer_path(@elemento), method: "get", class: 'btn btn-primary' %>
</div>

app/views/transfers/new.html.erb
<h1 class="centro">Nuevo Traspaso</h1>

<%= render 'form' %>
<div class="mo0a">
<%= button_to 'Atras', elemento_transfers_path, method: "get", class: 'btn btn-primary' %>
</div>

app/views/transfers/show.html.erb
<div class="showcentro">
<%#<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre Elemento:</strong>
  <%= @transfer.elemento.nombre %>
</p>

<p>
	<strong>Cuentadante Origen:</strong>
	<%= @transfer.cuentaorigen %>
</p>

<p>
  <strong>Cuentadante Destino:</strong>
  <%= @transfer.cuentadante.nombre %>
</p>

<p>
  <strong>Fecha Traspaso:</strong>
  <%= @transfer.fechaTraspaso %>
</p>
</div>
<div class="contdiv3">
	<div class="mo0a1-2">
	<%= button_to 'Editar', edit_elemento_transfer_path(@elemento,@transfer), method: "get", class: 'btn btn-warning' %>
	</div>
	<div class="mo0a2">
	<%= button_to 'Atras', elemento_transfers_path, method: "get", class: 'btn btn-success' %>
	</div>
</div>